---
- name: "Install Docker dependencies"
  ansible.builtin.yum:
    name: yum-utils
    state: present
    update_cache: true

- name: "Add Docker repository"
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/centos/docker-ce.repo
    dest: /etc/yum.repos.d
    owner: root
    group: root
    mode: '0644'

- name: "Install Docker Engine, containerd, Docker Compose"
  ansible.builtin.yum:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present
  notify: Restart Docker

- name: "Add in Docker group user: {{ docker_user }}"
  ansible.builtin.user:
    name: "{{ docker_user }}"
    append: true
    groups: docker
