---
- name: "Update cache"
  ansible.builtin.apt:
    update_cache: true

- name: "Install dependencies"
  ansible.builtin.apt:
    pkg:
      - curl
      - ca-certificates

- name: "Create directories"
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0644'
    recurse: true
    owner: vagrant
    group: vagrant

- name: "Download gpg"
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /etc/apt/keyrings/docker.asc
    mode: a+r

- name: "Add the repository to APT sources"
  ansible.builtin.copy:
    content: "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    dest: /etc/apt/sources.list.d/docker.list
    mode: '0644'

- name: "Update cache"
  ansible.builtin.apt:
    update_cache: true

- name: "Install Docker components"
  ansible.builtin.apt:
    pkg:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin

- name: "Add in Docker group user: {{ docker_user }}"
  ansible.builtin.user:
    append: true
    group: docker
    name: "{{ docker_user }}"
